sonar.projectKey=credit-circuit
sonar.projectName=Credit Circuit
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/checks
sonar.java.source=17
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=backend/target/surefire-reports,backend/target/failsafe-reports
sonar.javascript.lcov.reportPaths=outputs/03_Verification/lcov.info
