package com.marvens.capstone;

import java.util.UUID;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.marvens.capstone.dto.RegisterRequest;
import com.marvens.capstone.dto.LoginRequest;
import com.marvens.capstone.dto.PurchaseRequest;
import com.fasterxml.jackson.databind.JsonNode;
import com.marvens.capstone.repository.DemoCardRepository;
import com.marvens.capstone.service.AuthService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrint;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.web.servlet.MockMvc;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.any;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc(print = MockMvcPrint.NONE)
class AuthIT extends SecurityTestSupport {
    @Autowired MockMvc mvc;
    @Autowired ObjectMapper json;
    @Autowired JdbcTemplate jdbc;
    @Autowired AuthService auth;
    @MockitoSpyBean DemoCardRepository cards;
    String email;
    String password;
    String otherEmail;

    @BeforeEach
    void fixtures() {
        email = "auth-check-" + UUID.randomUUID() + "@example.test";
        otherEmail = "auth-check-" + UUID.randomUUID() + "@example.test";
        password = UUID.randomUUID().toString();
    }

    @AfterEach
    void cleanup() {
        reset(cards);
        // Only the identity generated by this test is removed; existing demo data stays intact.
        for (String fixtureEmail : new String[] {email, otherEmail}) {
            jdbc.update("DELETE FROM card_transactions WHERE account_id IN (SELECT a.id FROM credit_accounts a JOIN app_users u ON a.user_id=u.id WHERE u.email=?) AND type='REFUND'", fixtureEmail);
            jdbc.update("DELETE FROM card_transactions WHERE account_id IN (SELECT a.id FROM credit_accounts a JOIN app_users u ON a.user_id=u.id WHERE u.email=?)", fixtureEmail);
            jdbc.update("DELETE FROM demo_cards WHERE account_id IN (SELECT a.id FROM credit_accounts a JOIN app_users u ON a.user_id=u.id WHERE u.email=?)", fixtureEmail);
            jdbc.update("DELETE FROM credit_accounts WHERE user_id IN (SELECT id FROM app_users WHERE email=?)", fixtureEmail);
            jdbc.update("DELETE FROM app_users WHERE email=?", fixtureEmail);
        }
    }

    RegisterRequest request() {
        RegisterRequest request = new RegisterRequest();
        request.displayName = "Authentication Check";
        request.email = email;
        request.password = password;
        return request;
    }

    @Test
    void registrationLoginAndCurrentUserUseRealMysqlAndSignedJwt() throws Exception {
        String registration = json.createObjectNode().put("displayName", "Authentication Check").put("email", email).put("password", password).toString();
        mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration))
                .andExpect(status().isCreated()).andExpect(jsonPath("$.role").value("USER"));
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM demo_cards c JOIN credit_accounts a ON c.account_id=a.id JOIN app_users u ON a.user_id=u.id WHERE u.email=?", Integer.class, email)).isEqualTo(1);
        String hash = jdbc.queryForObject("SELECT password_hash FROM app_users WHERE email=?", String.class, email);
        assertThat(hash != null && hash.startsWith("$2a$12$")).isTrue();
        mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration)).andExpect(status().isConflict());
        String login = json.createObjectNode().put("email", email).put("password", password).toString();
        String result = mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content(login))
                .andExpect(status().isOk()).andReturn().getResponse().getContentAsString();
        String token = json.readTree(result).path("accessToken").asText();
        mvc.perform(get("/api/auth/me").header("Authorization", "Bearer " + token)).andExpect(status().isOk()).andExpect(jsonPath("$.email").value(email));
        mvc.perform(get("/api/accounts").header("Authorization", "Bearer " + token)).andExpect(status().isOk()).andExpect(jsonPath("$[0].availableCredit").value(1000));
        mvc.perform(get("/api/admin/accounts").header("Authorization", "Bearer " + token)).andExpect(status().isForbidden());
    }

    @Test
    void aCardWriteFailureRollsBackUserAndAccountCreation() {
        doThrow(new IllegalStateException("fixture-write-failure")).when(cards).save(any());
        RegisterRequest registration = request();
        assertThatThrownBy(() -> auth.register(registration)).isInstanceOf(IllegalStateException.class);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM app_users WHERE email=?", Integer.class, email)).isZero();
    }

    @Test
    void twoRegisteredCustomersUseTheirOwnStableAssignedCards() throws Exception {
        RegisterRequest firstRegistration = request();
        auth.register(firstRegistration);
        RegisterRequest secondRegistration = request();
        secondRegistration.email = otherEmail;
        auth.register(secondRegistration);

        String firstToken = signIn(email);
        String secondToken = signIn(otherEmail);
        long firstAccountId = getJson("/api/accounts", firstToken).get(0).path("id").asLong();
        long secondAccountId = getJson("/api/accounts", secondToken).get(0).path("id").asLong();
        String firstNumber = "0000" + String.format("%012d", firstAccountId);
        String secondNumber = "0000" + String.format("%012d", secondAccountId);
        assertThat(firstNumber.equals(secondNumber)).isFalse();
        JsonNode firstCard = getJson("/api/accounts/" + firstAccountId + "/cards", firstToken).get(0);
        JsonNode secondCard = getJson("/api/accounts/" + secondAccountId + "/cards", secondToken).get(0);
        assertThat(firstCard.path("numberEntryHint").asText()).contains("account ID " + firstAccountId);
        assertThat(getJson("/api/accounts/" + firstAccountId + "/cards", signIn(email)).get(0)).isEqualTo(firstCard);

        PurchaseRequest firstPurchase = assignedPurchase(firstCard, firstNumber);
        firstPurchase.testCardNumber = secondNumber;
        submitAssignedPurchase(firstAccountId, firstToken, firstPurchase, 400);
        firstPurchase.testCardNumber = firstNumber;
        firstPurchase.cardId = secondCard.path("id").asLong();
        submitAssignedPurchase(firstAccountId, firstToken, firstPurchase, 404);
        firstPurchase.cardId = firstCard.path("id").asLong();
        submitAssignedPurchase(firstAccountId, secondToken, firstPurchase, 404);
        assertThat(getJson("/api/accounts/" + firstAccountId + "/transactions", firstToken).path("totalElements").asInt()).isZero();
        assertThat(getJson("/api/accounts", firstToken).get(0).path("outstandingBalance").decimalValue()).isZero();

        JsonNode firstResult = submitAssignedPurchase(firstAccountId, firstToken, firstPurchase, 201);
        assertThat(firstResult.path("transaction").path("status").asText()).isEqualTo("APPROVED");
        JsonNode replay = submitAssignedPurchase(firstAccountId, signIn(email), firstPurchase, 200);
        assertThat(replay.path("transaction").path("id")).isEqualTo(firstResult.path("transaction").path("id"));
        assertThat(getJson("/api/accounts/" + firstAccountId + "/transactions", firstToken).path("totalElements").asInt()).isEqualTo(1);
        JsonNode secondResult = submitAssignedPurchase(secondAccountId, secondToken,
                assignedPurchase(secondCard, secondNumber), 201);
        assertThat(secondResult.path("transaction").path("status").asText()).isEqualTo("APPROVED");
        assertThat(getJson("/api/accounts", firstToken).get(0).path("outstandingBalance").decimalValue()).isEqualByComparingTo("1.00");
        assertThat(getJson("/api/accounts", secondToken).get(0).path("outstandingBalance").decimalValue()).isEqualByComparingTo("1.00");
    }

    private String signIn(String customerEmail) {
        LoginRequest request = new LoginRequest();
        request.email = customerEmail;
        request.password = password;
        return auth.login(request).accessToken;
    }

    private JsonNode getJson(String path, String token) throws Exception {
        String result = mvc.perform(get(path).header("Authorization", "Bearer " + token))
                .andExpect(status().isOk()).andReturn().getResponse().getContentAsString();
        return json.readTree(result);
    }

    private PurchaseRequest assignedPurchase(JsonNode assignedCard, String fictionalNumber) {
        PurchaseRequest request = TestData.purchase(assignedCard.path("id").asLong(), "1.00");
        request.testCardNumber = fictionalNumber;
        request.expiryMonth = assignedCard.path("expiryMonth").asInt();
        request.expiryYear = assignedCard.path("expiryYear").asInt();
        return request;
    }

    private JsonNode submitAssignedPurchase(long accountId, String token, PurchaseRequest request,
            int expectedStatus) throws Exception {
        String result = mvc.perform(post("/api/accounts/" + accountId + "/purchases")
                .header("Authorization", "Bearer " + token).contentType(MediaType.APPLICATION_JSON)
                .content(TestData.purchaseJson(request).toString()))
                .andExpect(status().is(expectedStatus)).andReturn().getResponse().getContentAsString();
        assertThat(result).doesNotContain(request.testCardNumber, "testSecurityCode", "passwordHash");
        return json.readTree(result);
    }
}
