package com.marvens.capstone;

import java.util.UUID;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.marvens.capstone.dto.RegisterRequest;
import com.marvens.capstone.repository.DemoCardRepository;
import com.marvens.capstone.service.AuthService;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.web.servlet.MockMvc;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc(print = MockMvcPrint.NONE)
class AuthIT extends SecurityTestSupport {
    @Autowired MockMvc mvc;
    @Autowired ObjectMapper json;
    @Autowired JdbcTemplate jdbc;
    @Autowired AuthService auth;
    @MockitoSpyBean DemoCardRepository cards;
    String email;
    String password;

    @BeforeEach
    void fixtures() { email = "auth-check-" + UUID.randomUUID() + "@example.test"; password = UUID.randomUUID().toString(); }

    @AfterEach
    void cleanup() {
        reset(cards);
        // Only the identity generated by this test is removed; existing demo data stays intact.
        jdbc.update("DELETE FROM demo_cards WHERE account_id IN (SELECT a.id FROM credit_accounts a JOIN app_users u ON a.user_id=u.id WHERE u.email=?)", email);
        jdbc.update("DELETE FROM credit_accounts WHERE user_id IN (SELECT id FROM app_users WHERE email=?)", email);
        jdbc.update("DELETE FROM app_users WHERE email=?", email);
    }

    RegisterRequest request() {
        RegisterRequest request = new RegisterRequest();
        request.displayName = "Authentication Check"; request.email = email; request.password = password;
        return request;
    }

    @Test
    void registrationLoginAndCurrentUserUseRealMysqlAndSignedJwt() throws Exception {
        String registration = json.createObjectNode().put("displayName", "Authentication Check").put("email", email).put("password", password).toString();
        mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration))
                .andExpect(status().isCreated()).andExpect(jsonPath("$.role").value("USER"));
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM demo_cards c JOIN credit_accounts a ON c.account_id=a.id JOIN app_users u ON a.user_id=u.id WHERE u.email=?", Integer.class, email)).isEqualTo(1);
        String hash = jdbc.queryForObject("SELECT password_hash FROM app_users WHERE email=?", String.class, email);
        assertThat(hash != null && hash.startsWith("$2a$12$")).isTrue();
        mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content(registration)).andExpect(status().isConflict());
        String login = json.createObjectNode().put("email", email).put("password", password).toString();
        String result = mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content(login))
                .andExpect(status().isOk()).andReturn().getResponse().getContentAsString();
        String token = json.readTree(result).path("accessToken").asText();
        mvc.perform(get("/api/auth/me").header("Authorization", "Bearer " + token)).andExpect(status().isOk()).andExpect(jsonPath("$.email").value(email));
        mvc.perform(get("/api/accounts").header("Authorization", "Bearer " + token)).andExpect(status().isOk()).andExpect(jsonPath("$[0].availableCredit").value(1000));
        mvc.perform(get("/api/admin/accounts").header("Authorization", "Bearer " + token)).andExpect(status().isForbidden());
    }

    @Test
    void aCardWriteFailureRollsBackUserAndAccountCreation() {
        doThrow(new IllegalStateException("fixture-write-failure")).when(cards).save(any());
        assertThatThrownBy(() -> auth.register(request())).isInstanceOf(IllegalStateException.class);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM app_users WHERE email=?", Integer.class, email)).isZero();
    }
}
